# Generated by Django 4.1.7 on 2023-04-16 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0003_project_deleted_at_project_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='issue_tracker.status', verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
